/**
 * Seed script — inserts all apartment listings into Supabase.
 * Run once after the migration:
 *   npx ts-node --project tsconfig.json supabase/seed-listings.ts
 *
 * Or just paste the listings JSON into the Supabase Table Editor.
 */

const SUPABASE_URL = 'https://qrynqscwtctqbasivcvb.supabase.co'
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyeW5xc2N3dGN0cWJhc2l2Y3ZiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MDU5MDU3MywiZXhwIjoyMDU2MTY2NTczfQ.c2nnOxrj98uIGzAHBFodsEh6VWlWavjgM75WGYBgcYA'

const LISTINGS = [
  { id:'anthem', name:'Anthem PDX', addr:'1313 E Burnside · Kerns', price:'From $1,953', pn:'studio–2BR · built 2020', type:'apartment', beds:'2BR', score:78, status:'ok', isNew:true, lat:45.5236, lng:-122.6545, gradient:'linear-gradient(135deg,#1a1a2e,#0f3460)', rows:[{l:'Natural light',v:'Big windows',d:'g'},{l:'Kitchen',v:'Quartz + stainless',d:'g'},{l:'In-unit W/D',v:'Yes',d:'g'},{l:'Flooring',v:'Wood-look plank',d:'g'},{l:'2BR',v:'Available',d:'g'},{l:'AC',v:'In rent',d:'g'},{l:'Walk/Bike',v:'97/100',d:'g'},{l:'Pets',v:'Yes, breed restrictions',d:'y'}], flags:[{t:'Up to 8 weeks free',c:'fb'},{t:'Utilities not included',c:'fa'}], link:'https://www.anthempdx.com', note:"Burnside Corridor — Portland's best eastside strip. Peloton, yoga room, courtyard firepit.", mgmt:{name:'Avenue5 Residential',phone:'(971) 254-4598',email:'anthem@avenue5apt.com',hours:'M–F 10–6 · Sat–Sun 10–5'} },
  { id:'homma', name:'HOMMA HAUS Mt Tabor', addr:'5115 E Burnside · N Tabor', price:'$2,995/mo', pn:'2BR/2.5BA · 1,150 sqft · smart home', type:'apartment', beds:'2BR', score:74, status:'ok', isNew:true, lat:45.5232, lng:-122.6044, gradient:'linear-gradient(135deg,#2d1b69,#11998e)', rows:[{l:'Natural light',v:'Skylight + large windows',d:'g'},{l:'Kitchen',v:'Corian · gas · dishwasher',d:'g'},{l:'In-unit W/D',v:'Full-size upstairs',d:'g'},{l:'2BR',v:'Yes + 2.5 baths',d:'g'},{l:'Seismic',v:'Built 2022',d:'g'},{l:'Pets',v:'2 small ($50/mo)',d:'y'}], flags:[{t:'No availability yet — ask for June',c:'fa'},{t:'Above $2k budget',c:'fa'}], link:'https://www.apartments.com/homma-haus-mount-tabor-smart-home-portland-or/stf0wj6/', note:'Smart home townhomes by Green Hammer. Near Mt Tabor Park.', mgmt:{name:'Edge Asset Management',phone:'(503) 926-8021',hours:'By appointment'} },
  { id:'aoe', name:'Atomic Orchard Experiment', addr:'2510 NE Sandy · Kerns', price:'$1,805–$1,999', pn:'1BR · utilities separate', type:'apartment', beds:'1BR', score:72, status:'ok', isNew:false, lat:45.5317, lng:-122.6388, gradient:'linear-gradient(135deg,#f093fb,#f5576c,#fda085)', rows:[{l:'Layout',v:'Split-level loft · stairs',d:'g'},{l:'Natural light',v:'Floor-to-ceiling windows',d:'g'},{l:'Kitchen',v:'Quartz · dishwasher',d:'g'},{l:'In-unit W/D',v:'Full-size front-load',d:'g'},{l:'Flooring',v:'Wood laminate + concrete',d:'y'},{l:'2BR',v:'1BR only',d:'y'},{l:'Pets',v:'Dogs + cats ($300)',d:'g'}], flags:[{t:'Confirmed split-level layout',c:'fb'},{t:'Was in foreclosure — new mgmt ~Feb 2026',c:'fr'},{t:'Street parking only · breakins reported',c:'fr'}], link:'https://www.apartments.com/atomic-orchard-experiment-portland-or/9bwstf4/', note:'Best loft layout in Portland. New mgmt Feb 2026. Street parking only — leave nothing visible.', mgmt:{name:'New mgmt ~Feb 2026',phone:'Call building directly',hours:'Verify first'} },
  { id:'everettstlofts', name:'Everett Street Lofts', addr:'2821 NE Everett · Kerns', price:'$1,225–$1,450', pn:'Studio–1BR · in-unit W/D · built 2016', type:'apartment', beds:'1BR', score:78, status:'ok', isNew:true, lat:45.5266, lng:-122.6355, gradient:'linear-gradient(135deg,#373b44,#4286f4)', rows:[{l:'Layout',v:'Split-level units available',d:'g'},{l:'Natural light',v:'Energy-efficient windows',d:'g'},{l:'Kitchen',v:'Quartz · stainless',d:'g'},{l:'In-unit W/D',v:'Yes · full-size',d:'g'},{l:'Flooring',v:'Hardwood-style',d:'g'},{l:'2BR',v:'Studio + 1BR only',d:'y'},{l:'Pets',v:'Yes · dog wash',d:'g'}], flags:[{t:'Split-level confirmed per Reddit',c:'fb'},{t:'No 2BR',c:'fb'}], link:'https://www.portland-apartment-living.com/communities/everett-street-lofts/', note:'Same neighborhood as AOE, split-level confirmed. Great price, in-unit W/D, hardwood floors.', mgmt:{name:'Portland Apartment Living',phone:'(503) 726-7220 ext 1'} },
  { id:'moderabelmont', name:'Modera Belmont', addr:'685 SE Belmont · Buckman', price:'From $1,480', pn:'Studio–2BR · 457–1,230 sqft · 2018', type:'apartment', beds:'2BR', score:76, status:'ok', isNew:true, lat:45.5155, lng:-122.6500, gradient:'linear-gradient(135deg,#ff6b6b,#feca57)', rows:[{l:'Natural light',v:'Floor-to-ceiling windows',d:'g'},{l:'Kitchen',v:'Quartz · eco floors',d:'g'},{l:'In-unit W/D',v:'Yes',d:'g'},{l:'2BR',v:'Up to 1,230 sqft',d:'g'},{l:'Rooftop',v:'Mt Hood + river views',d:'g'},{l:'Pets',v:'Yes · pet spa',d:'g'}], flags:[{t:'Price drops seen recently',c:'fb'}], link:'https://www.moderabelmont.com/', note:'Floor-to-ceiling windows, rooftop with Mt Hood views. Well-reviewed management.', mgmt:{name:'Mill Creek Residential',hours:'M–F 10–6 · Sat 10–5 · moderabelmont.com'} },
  { id:'waldorf', name:'Waldorf Apartments', addr:'833 NE Schuyler · Irvington', price:'Call for price', pn:'KBC Mgmt · +$105/mo utilities', type:'apartment', beds:'2BR', score:68, status:'ok', isNew:false, lat:45.5381, lng:-122.6471, gradient:'linear-gradient(135deg,#667eea,#764ba2)', rows:[{l:'Kitchen',v:'Retro checkered',d:'y'},{l:'In-unit W/D',v:'Confirm',d:'y'},{l:'Flooring',v:'Hardwood',d:'g'},{l:'2BR',v:'Yes',d:'g'},{l:'AC',v:'Confirmed',d:'g'},{l:'Pets',v:'Dogs + cats',d:'g'}], flags:[{t:'Call to get price',c:'fa'}], link:'https://www.kbcmgmt.com/listings/detail/48b2cfd2-1cd4-45e3-a72a-f1da1f97032f', note:'Best vintage 2BR character on the list. Near NE Broadway. Confirm laundry + price first.', mgmt:{name:'KBC Management',phone:'(503) 287-6876',hours:'M–F business hours'} },
  { id:'cookstreet', name:'Cook Street', addr:'107 N Cook · Williams District', price:'From $1,335', pn:'Studio–2BR · 490–983 sqft · 2016', type:'apartment', beds:'2BR', score:71, status:'ok', isNew:true, lat:45.545, lng:-122.67, gradient:'linear-gradient(135deg,#0f2027,#2c5364)', rows:[{l:'Natural light',v:'Picture windows',d:'g'},{l:'Kitchen',v:'Luxury finishes',d:'y'},{l:'In-unit W/D',v:'Confirm',d:'y'},{l:'2BR',v:'Up to 983 sqft',d:'g'},{l:'Eco',v:'Natural NW materials',d:'g'},{l:'Pets',v:'No weight limit',d:'g'}], flags:[{t:'Confirm in-unit W/D',c:'fa'}], link:'https://cookstreetportland.com/', note:'Williams District — one block from Mississippi. Picture windows, eco-build, no pet weight limit.', mgmt:{name:'Cook Street Leasing',hours:'cookstreetportland.com'} },
  { id:'buckmancourt', name:'Buckman Court', addr:'1955 SE Morrison · Buckman', price:'$1,250–$1,395', pn:'Studio–2BR + 6 townhomes · 1970', type:'apartment', beds:'2BR', score:71, status:'ok', isNew:true, lat:45.5188, lng:-122.6452, gradient:'linear-gradient(135deg,#5C258D,#4389A2)', rows:[{l:'Layout',v:'6 two-story townhomes',d:'g'},{l:'In-unit W/D',v:'No — shared',d:'r'},{l:'2BR',v:'Yes',d:'g'},{l:'Pets',v:'No pets',d:'r'},{l:'Price',v:'Best-value 2BR',d:'g'}], flags:[{t:'Ask for townhome units specifically',c:'fb'},{t:'No pets',c:'fr'},{t:'No in-unit laundry',c:'fr'}], link:'https://www.portland-apartment-living.com/communities/buckman-court/', note:'6 two-story townhomes likely have split-level layout. Best 2BR price. No pets + shared laundry.', mgmt:{name:'Portland Apartment Living',phone:'(503) 726-7220 ext 1'} },
  { id:'asalofts', name:'ASA Flats + Lofts', addr:'1200 NW Marshall · Pearl District', price:'$1,346–$2,853', pn:'Studio–2BR · 15+ split-level units', type:'apartment', beds:'2BR', score:70, status:'ok', isNew:true, lat:45.5289, lng:-122.6832, gradient:'linear-gradient(135deg,#232526,#414345)', rows:[{l:'Layout',v:'15–20 split-level units',d:'g'},{l:'Natural light',v:'Floor-to-ceiling windows',d:'g'},{l:'Kitchen',v:'Quartz · stainless',d:'g'},{l:'2BR',v:'Yes · up to $2,853',d:'g'},{l:'Rooftop',v:'16th floor · fire pit',d:'g'},{l:'Pets',v:'Yes · 75lb max',d:'g'}], flags:[{t:'15–20 split-level units per Reddit',c:'fb'},{t:'Pearl District — higher price',c:'fa'}], link:'https://www.liveatasa.com/asa-flats-lofts-portland-or/', note:'Largest loft-unit inventory in Portland per Reddit. Ask specifically for mezzanine floorplans.', mgmt:{name:'ASA Flats Leasing',phone:'(503) 755-9217',hours:'M–F 9:30–6 · Sat 9–6 · Sun 11–4'} },
  { id:'park19', name:'Park 19', addr:'550 NW 19th · Alphabet District', price:'2BR from $2,512', pn:'Studio–2BR · 529–1,168 sqft', type:'apartment', beds:'2BR', score:65, status:'ok', isNew:true, lat:45.5270, lng:-122.6928, gradient:'linear-gradient(135deg,#2c3e50,#3498db)', rows:[{l:'Natural light',v:'Large windows · park views',d:'g'},{l:'In-unit W/D',v:'Confirm',d:'y'},{l:'2BR',v:'From $2,512',d:'y'},{l:'Management',v:'Greystar · excellent',d:'g'},{l:'Walk',v:'Couch + Washington Park',d:'g'}], flags:[{t:'2BR above $2k',c:'fa'},{t:'NW Portland — not eastside',c:'fb'}], link:'https://www.livepark19.com/', note:'Residents stay for years. Couch Park views, walkable to Forest Park.', mgmt:{name:'Greystar',hours:'livepark19.com'} },
  { id:'revere', name:'Revere', addr:'3309 N Mississippi · Boise', price:'$1,356–$2,464+', pn:'Studio–2BR · 570–1,097 sqft · 2019', type:'apartment', beds:'2BR', score:67, status:'ok', isNew:true, lat:45.5476, lng:-122.6741, gradient:'linear-gradient(135deg,#1a1a2e,#0f3460)', rows:[{l:'Layout',v:'Ground-floor split-level 1BR',d:'g'},{l:'Kitchen',v:'Stainless · gas stove',d:'g'},{l:'In-unit W/D',v:'Yes',d:'g'},{l:'Amenities',v:'Bouldering wall · sauna',d:'g'},{l:'Pets',v:'Yes · no weight limit',d:'g'}], flags:[{t:'Split-level units are ground floor only',c:'fb'},{t:'Car break-ins — street parking',c:'fr'}], link:'https://www.reverepdx.com/', note:'Mississippi Ave — best N Portland strip. Bouldering wall on-site. Ground-floor split-level 1BRs only.', mgmt:{name:'Avenue5 Residential',phone:'(503) 227-2787',email:'revere@avenue5apt.com',hours:'M–F 9–6 · Sat 10–5'} },
  { id:'parkview', name:'Parkview Apartments', addr:"1640 NE Irving · Sullivan's Gulch", price:'From $1,495', pn:'2BR 950sqft · Historic Registry · 1941', type:'apartment', beds:'2BR', score:64, status:'ok', isNew:true, lat:45.5289, lng:-122.6567, gradient:'linear-gradient(135deg,#4ecdc4,#093637)', rows:[{l:'Natural light',v:'Picture windows',d:'g'},{l:'In-unit W/D',v:'No — basement',d:'r'},{l:'Flooring',v:'Beautiful hardwood',d:'g'},{l:'2BR',v:'950 sqft',d:'g'},{l:'Courtyard',v:'5-acre garden',d:'g'}], flags:[{t:'No in-unit laundry',c:'fr'},{t:'Steam heat — ask about drafts',c:'fa'}], link:'https://www.apartments.com/parkview-apartments-portland-or/sb2rbt6/', note:'Gorgeous historic property with garden courtyard. Best-priced 2BR on list. Shared laundry only.', mgmt:{name:'See listing for contact',hours:'apartments.com listing'} },
  { id:'fortyone11', name:'Forty One 11', addr:'4111 NE MLK · Alberta/King', price:'From $1,199', pn:'Studio–2BR · 394–931 sqft · 2019', type:'apartment', beds:'2BR', score:62, status:'ok', isNew:true, lat:45.556, lng:-122.664, gradient:'linear-gradient(135deg,#833ab4,#fcb045)', rows:[{l:'Natural light',v:'Unknown — ask',d:'y'},{l:'In-unit W/D',v:'Unknown — ask',d:'y'},{l:'2BR',v:'Up to 931 sqft',d:'g'},{l:'Price',v:'Very affordable',d:'g'}], flags:[{t:'Many details unknown — call to confirm',c:'fa'}], link:'https://www.fortyone11pdx.com/', note:'Alberta Arts / King — one of the coolest areas. Very competitive price for 2BR.', mgmt:{name:'Forty One 11 Leasing',hours:'fortyone11pdx.com'} },
  { id:'kailash', name:'Kailash Ecovillage', addr:'SE Portland · Creston-Kenilworth', price:'Waitlist', pn:'1–2BR · rental model', type:'cohousing', beds:'1–2BR', score:62, status:'ok', isNew:true, lat:45.493, lng:-122.63, gradient:'linear-gradient(135deg,#56ab2f,#a8e063)', rows:[{l:'Community',v:'Solar intentional',d:'g'},{l:'Shared spaces',v:'Treehouse · gardens',d:'g'},{l:'In-unit W/D',v:'Building laundry',d:'y'},{l:'2BR',v:'Some units',d:'y'}], flags:[{t:'Waitlist — contact ASAP for June',c:'fa'}], link:'https://www.kailashecovillage.org/housing', note:'Best cohousing fit for your values. Rental model — no ownership needed.', mgmt:{name:'Kailash Ecovillage',hours:'kailashecovillage.org/contact'} },
  { id:'cascadia', name:'Cascadia Commons', addr:'SW Portland · Raleigh Hills', price:'$1,800/mo', pn:'1BR 675sqft · water/sewer/HOA incl', type:'cohousing', beds:'1BR', score:58, status:'ok', isNew:true, lat:45.4896, lng:-122.78, gradient:'linear-gradient(135deg,#1d976c,#93f9b9)', rows:[{l:'Natural light',v:"Vaulted 12' ceilings",d:'g'},{l:'In-unit W/D',v:'Yes',d:'g'},{l:'Community',v:'26 households since 1999',d:'g'},{l:'Shared spaces',v:'Dining hall · workshop',d:'g'}], flags:[{t:'SW Portland',c:'fa'},{t:'Monthly work parties required',c:'fb'}], link:'https://cascadiacommons.com/units-for-sale-or-rent/', note:'Available now $1,800/mo all-in.', mgmt:{name:'Cascadia Commons',phone:'(503) 512-0662',email:'JwhateverG@gmail.com'} },
  { id:'belmont21', name:'2121 Belmont', addr:'2121 SE Belmont · Buckman', price:'From $1,977', pn:'2BR ~$2,500–$3,600', type:'apartment', beds:'1–2BR', score:61, status:'ok', isNew:false, lat:45.5162, lng:-122.643, gradient:'linear-gradient(135deg,#fc4a1a,#f7b733)', rows:[{l:'Natural light',v:'Open-concept, glowing',d:'g'},{l:'Kitchen',v:'Condo-grade finishes',d:'g'},{l:'In-unit W/D',v:'Likely',d:'y'},{l:'2BR',v:'Available (pricey)',d:'y'},{l:'Parking',v:'Underground garage',d:'g'}], flags:[{t:'Up to 6 weeks free',c:'fb'}], link:'https://www.2121belmontapts.com/', note:'Condo-grade Buckman build. Use the free weeks to offset 2BR cost.', mgmt:{name:'2121 Belmont Leasing',hours:'2121belmontapts.com'} },
  { id:'belmontdairy', name:'Belmont Dairy Lofts', addr:'3342 SE Morrison · Sunnyside', price:'From $1,258', pn:'1–2BR · income-qualified', type:'apartment', beds:'2BR', score:48, status:'ok', isNew:true, lat:45.5180, lng:-122.6390, gradient:'linear-gradient(135deg,#d4a373,#a0522d)', rows:[{l:'Layout',v:'22-ft ceilings · skylights',d:'g'},{l:'In-unit W/D',v:'No — shared',d:'r'},{l:'2BR',v:'1,004–1,486 sqft',d:'g'},{l:'Flooring',v:'Hardwood',d:'g'}], flags:[{t:'⚠ Income-qualified — verify eligibility',c:'fr'},{t:'Mixed management reviews',c:'fr'},{t:'No in-unit laundry',c:'fr'}], link:'https://www.belmontdairy.com/', note:'Stunning ceilings and skylights. BUT: income caps — verify eligibility first.', mgmt:{name:'Cirrus Asset Management',hours:'belmontdairy.com'} },
  { id:'east12', name:'East 12 Lofts', addr:'1100 SE 12th · Buckman', price:'From $1,195', pn:'Studio/1BR · 380–445 sqft · 2014', type:'apartment', beds:'Studio/1BR', score:63, status:'ok', isNew:true, lat:45.5159, lng:-122.6583, gradient:'linear-gradient(135deg,#373B44,#4286f4)', rows:[{l:'Natural light',v:'Oversized windows',d:'g'},{l:'Kitchen',v:'Quartz · stainless',d:'g'},{l:'In-unit W/D',v:'Stacked',d:'g'},{l:'2BR',v:'No — studio/1BR only',d:'r'},{l:'Amenities',v:'Rooftop · fitness',d:'g'}], flags:[{t:'Studio/1BR only',c:'fr'},{t:'1 month free select units',c:'fb'}], link:'https://www.liveeast12.com/', note:'Buckman — steps from food carts. Units small (380–445 sqft) but well finished.', mgmt:{name:'East 12 Leasing',hours:'liveeast12.com'} },
]

async function seed() {
  console.log(`Seeding ${LISTINGS.length} listings…`)
  const rows = LISTINGS.map(l => ({ id: l.id, data: l, updated_at: new Date().toISOString() }))

  const res = await fetch(`${SUPABASE_URL}/rest/v1/apartment_listings`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'apikey': SUPABASE_KEY,
      'Authorization': `Bearer ${SUPABASE_KEY}`,
      'Prefer': 'resolution=merge-duplicates',
    },
    body: JSON.stringify(rows),
  })

  if (!res.ok) {
    const err = await res.text()
    console.error('Seed failed:', res.status, err)
    process.exit(1)
  }

  console.log('✓ Seeded', rows.length, 'listings successfully')
}

seed()
