-- Seed entries (organized by project/org name, years only, roles in detail)
INSERT INTO site_entries (slug, title, org, date, url, github, role, tags, status, gradient, description, highlight, entry_type, sort_order) VALUES
('big-think', 'BIG THINK', 'Media & Strategy', '2022 – Present', 'https://bigthink.com', NULL, 'Social Strategy Lead (2026 – Present) · Editorial Social Media Manager (2024 – 2026)', '{"Content Strategy","Video Editing","Social Media","Analytics","GA4"}', 'live', 'gradient-card-1', 'Own cross-platform content strategy across Instagram, YouTube, and LinkedIn. Produce original video series, manage data pipelines from GA4 to membership revenue attribution. Previously managed editorial social presence, developed content calendars, audience growth strategies, and analytics reporting.', NULL, 'role', 0),
('curiosity-lab', 'CURIOSITY LAB', 'Big Think · Video Series', '2022 – Present', 'https://www.youtube.com/@bigthink', NULL, 'Creator, host, editor', '{"Video","Science Communication","Big Think"}', 'ongoing', 'gradient-card-2', 'An original video series for Big Think exploring the edges of science, consciousness, and human behavior — from MIT ultrasound consciousness research to the neuroscience of creativity. Written, produced, and presented by me.', '100M+ views across the channel', 'project', 1),
('audian', 'AUDIAN', 'Personal Project', '2024 – Present', 'https://audian.app', 'https://github.com/malvidah/audian', 'Solo — design, engineering', '{"Next.js","Playwright","Railway","Instagram API"}', 'live', 'gradient-card-3', 'A social analytics dashboard built to replace a paid Brandwatch subscription for Big Think. Features a split-pane staging queue with keyboard navigation, inline editing, bulk actions, and a self-hosted Playwright service for live Instagram screenshots.', 'Saves ~$600/mo vs. Brandwatch', 'project', 2),
('day-lab', 'DAY LAB', 'Personal Project', '2023 – Present', 'https://daylab.me', 'https://github.com/malvidah/lifeos', 'Solo — design, engineering', '{"Next.js 14","Supabase","Electron","iOS"}', 'live', 'gradient-card-4', 'A personal life OS for tracking health, tasks, meals, journal entries, and activity. Syncs Oura, Strava, Apple Health, and Google Calendar into a single unified view. Released as a Mac app (notarized DMG) and iOS (TestFlight).', 'Replaced 6 separate apps', 'project', 3),
('nas-company', 'NAS COMPANY', 'Media & Content', '2024', NULL, NULL, 'Project Manager (2024) · Host / Scriptwriter (2024)', '{"Media Strategy","Partnership Development","Scriptwriting","Video Production"}', 'past', 'gradient-card-1', 'Wrote and designed partnership proposals and content strategies that generated $1M+ in revenue and delivered 68M+ views and 100,000+ leads for clients. Developed content strategy, wrote viral scripts, filmed, and presented content for a client channel focused on science, tech, and AI that reached 7M+ people and 4x''d the client''s followers in 1 month.', '$1M+ revenue, 7M+ reach', 'role', 4),
('national-heritage-academies', 'NATIONAL HERITAGE ACADEMIES', 'Education', '2022 – 2023', NULL, NULL, 'Consultant', '{"Curriculum Design","AI in Education","Growth Marketing"}', 'past', 'gradient-card-2', 'Led the design of a new physical science curriculum and the safe implementation of AI tools in classrooms for one of the largest charter school operators in the world (100+ schools, 65K+ students, tuition free).', '100+ schools, 65K+ students', 'role', 5),
('curyte', 'CURYTE', 'EdTech Startup', '2021 – 2022', NULL, NULL, 'Co-Founder', '{"Product Marketing","Business Development","User Research"}', 'past', 'gradient-card-3', 'Founded and directed product marketing and business development for an education resource platform that uses AI to make lesson planning faster and easier for teachers and more accessible and engaging for students.', NULL, 'project', 6),
('academy-of-thought-and-industry', 'ACADEMY OF THOUGHT AND INDUSTRY', 'Education', '2021 – 2022', NULL, NULL, 'Community Lead & Science Guide', '{"Science Education","Curriculum Design","Leadership"}', 'past', 'gradient-card-4', 'Coordinated with head of San Francisco ATI schools to lead a Montessori high school with 5 teachers. Taught NGSS-aligned project-based curriculum for Chemistry, Physics, and Biology.', NULL, 'role', 7),
('san-francisco-unified', 'SAN FRANCISCO UNIFIED', 'Education', '2018 – 2021', NULL, NULL, 'Physics Lead & HSA Teacher (2019 – 2021) · Physics Teacher (2018 – 2019)', '{"Science Education","Curriculum Design","Storytelling"}', 'past', 'gradient-card-1', 'Led a team of 4 in designing and instructing curriculum for physics. Taught 3 sections of physics and 2 sections of senior-level public health. Led professional development for 100+ teachers on project-based learning. Collaborated with the Exploratorium, UCSF, and Stanford.', 'PD for 100+ teachers', 'role', 8),
('cercle', 'CERCLE', 'Music & Events', '2016 – 2018', NULL, NULL, 'Co-Founder', '{"Marketing","Event Production","Social Media","Branding"}', 'past', 'gradient-card-2', 'Helped found and raise initial funding for Cercle, a live-streaming and music event company. Collaborated on branding decisions, artist contacts, and event organization.', NULL, 'project', 9),
('bonn-university', 'BONN UNIVERSITY', 'Neuroscience', '2015 – 2017', NULL, NULL, 'Masters Student · Graduate Research Assistant', '{"Quantitative Research","Neuroscience"}', 'past', 'gradient-card-3', 'Master''s thesis in synaptic transmission and molecular correlates of learning and memory. Graduate research assistant conducting neuroscience research.', NULL, 'role', 10),
('salk-institute', 'SALK INSTITUTE', 'Neuroscience', '2015', NULL, NULL, 'Research Assistant', '{"Quantitative Research","Neuroscience"}', 'past', 'gradient-card-4', 'Assisted in data collection for a research paper published in Nature Neuroscience: Pathological priming causes developmental gene network heterochronicity in autistic subject-derived neurons.', 'Published in Nature Neuroscience', 'role', 11),
('ucsb', 'UC SANTA BARBARA', 'Research', '2012 – 2015', NULL, NULL, 'Undergraduate Research Assistant — Neuroscience Research Institute · Vision & Image Understanding Lab', '{"Neuroscience","Computer Vision","Research"}', 'past', 'gradient-card-1', 'Undergraduate research assistant across two labs: the Neuroscience Research Institute and the Vision & Image Understanding lab at UC Santa Barbara.', NULL, 'role', 12),
('scripps-research', 'SCRIPPS RESEARCH INSTITUTE', 'Biology', '2012', NULL, NULL, 'Research Assistant', '{"Research","Biology"}', 'past', 'gradient-card-2', 'Research assistant at The Scripps Research Institute in San Diego.', NULL, 'role', 13);

-- Seed about content
INSERT INTO site_about (key, value) VALUES
('about_1', 'I lead social strategy at Big Think, produce the Curiosity Lab video series, and build software tools for my own work — including a life OS and a social analytics platform.'),
('about_2', 'I think a lot about media, attention, and what it means to make something worth watching.'),
('contact_heading', 'Let''s talk.'),
('contact_body', 'Open to interesting conversations about media, AI, tools, or anything else that sits at the edge of something.');
